### ISSUE TITLE
postmap sasl_passwd

### ISSUE THREAD

**Issue by morinatsu** [Stouts/Stouts.postfix#6]
I need to execute these command.

chmod 400 /etc/postfix/sasl_passwd
postmap /etc/postfix/sasl_passwd 

not automated?

**Comment by morinatsu** [comment]
I understand what happens(and not happen).
I tried twice this Role.

-----
1st:

TASK: [Stouts.postfix | Configure postfix pt. 2] ******************************
changed: [192.168.1.201]

TASK: [Stouts.postfix | Configure postfix pt. 3] ******************************
failed: [192.168.1.201] =>  (Permission Denied)

-----
2nd (sudo: yes):

TASK: [Stouts.postfix | Configure postfix pt. 2] ******************************
ok: [192.168.1.201]

TASK: [Stouts.postfix | Configure postfix pt. 3] ******************************
skipping: [192.168.1.201]

-----

I want to change conditions to execute 'Configure postfix pt. 3'.

**Comment by klen** [comment]
Remove `/etc/postfix/sasl_passwd` and repeat the provision.
